### ISSUE TITLE
Error when make O=$TEGRA_KERNEL_OUT zImage

### ISSUE THREAD

**Issue by mrtortong** [Technica-Corporation/Tegra-Docker#1]
nvidia@tegra-ubuntu:~/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4$ sudo make O=$TEGRA_KERNEL_OUT zImage
[sudo] password for nvidia: 
make[1]: Entering directory '/kernel-out'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
drivers/platform/tegra/Kconfig:113:warning: ignoring type redefinition of 'TEGRA_SOCTHERM' from 'tristate' to 'boolean'
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
/home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4/scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[3]: *** [silentoldconfig] Error 1
/home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4/Makefile:531: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 2
make[1]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
make[1]: Leaving directory '/kernel-out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

**Comment by kgdad** [comment]
Looks like you are missing the .config file in the $TEGRA_KERNEL_OUT directory.  Make sure you copied one of the given .configs from Step 8:

> Copy the custom kernel config file (.config) into the $TEGRA_KERNEL_OUT directory. Use at a minimum this .config which will enable core Docker functionality, or this .config for additional options to potentially also get LXC and LXD working.

**Comment by mrtortong** [comment]
@kgdad 
         Not missing i convert from config to .config but still error.

nvidia@tegra-ubuntu:~/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4$ make O=~/build_root/kernel-out zImage
make[1]: Entering directory '/home/nvidia/build_root/kernel-out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
drivers/platform/tegra/Kconfig:113:warning: ignoring type redefinition of 'TEGRA_SOCTHERM' from 'tristate' to 'boolean'
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
  Using /home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4 as source for kernel
  /home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4 is not clean, please run 'make mrproper'
  in the '/home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4' directory.
/home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4/Makefile:983: recipe for target 'prepare3' failed
make[1]: *** [prepare3] Error 1
make[1]: Leaving directory '/home/nvidia/build_root/kernel-out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
nvidia@tegra-ubuntu:~/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4$ make mrproper O=~/build_root/kernel-out zImage
make[1]: Entering directory '/home/nvidia/build_root/kernel-out'
  CLEAN   scripts/basic
  CLEAN   scripts/kconfig
  CLEAN   include/config include/generated
  CLEAN   .config
  CHK     include/config/kernel.release
/bin/sh: 1: cannot open include/config/auto.conf: No such file
/home/nvidia/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4/Makefile:966: recipe for target 'include/config/kernel.release' failed
make[1]: *** [include/config/kernel.release] Error 2
make[1]: Leaving directory '/home/nvidia/build_root/kernel-out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
nvidia@tegra-ubuntu:~/build_root/Linux_for_Tegra/sources/kernel/kernel-4.4$

**Comment by mrtortong** [comment]
nvidia@tegra-ubuntu:~$ sudo apt-get install docker.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker.io is already the newest version (1.12.6-0ubuntu1~16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 216 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up docker.io (1.12.6-0ubuntu1~16.04.1) ...
addgroup: The group `docker' already exists as a system group. Exiting.
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker.io (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker.io
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kgdad** [comment]
@mrtortong looks like you were able to get your kernel built successfully.  

For your new issue I have seen this before on one of our servers, but don't remember the resolution.  What is the output of:
`sudo service docker status`

You can also try purging your current docker.io package (apt-get purge docker.io) and then trying to reinstall.

**Comment by mrtortong** [comment]
I try apt-get purge docker.io and reinstall.It still error.
nvidia@tegra-ubuntu:~$ uname -a
Linux tegra-ubuntu 4.4.15 #2 SMP PREEMPT Fri Jun 23 10:38:48 ICT 2017 aarch64 aarch64 aarch64 GNU/Linux
nvidia@tegra-ubuntu:~$ uname -r
4.4.15

It does not show 4.4.15-docker.Because?

**Comment by kgdad** [comment]
Make sure you have copied all of the kernel files you created over to the TX-2 and rebooted.  Need to copy the zImage, Image, dtb's, and the kernel modules.
