### ISSUE TITLE
TensorRT in Docker using Xavier

### ISSUE THREAD

**Issue by statikkkkk** [Technica-Corporation/Tegra-Docker#14]
Hi,

I am trying to get TensorRT working with Xavier. The provided `tx2-docker` wrapper works perfectly with `Tensorflow` until I tried to get TensorRT working w/ `Tensorflow`.

System version: 

- JetPack 4.2
- CUDA 10.0
- Python 3.6

The error I got is:
```
2019-06-20 22:49:25.752103: F tensorflow/contrib/tensorrt/log/trt_logger.cc:42] DefaultLogger Assertion failed: eglCreateStreamKHR != nullptr
dla/eglUtils.cpp:61
Aborting...
```

I am able to run the script perfectly fine outside Docker, but have this issue if running with Docker.

**Comment by wangshankun** [comment]
same issue

**Comment by statikkkkk** [comment]
Closed due to official support for GPU Docker in JetPack is supported. 

https://developer.nvidia.com/embedded/jetpack

From Nvidia's website:
> JetPack 4.2.1 also introduced two beta features: NVIDIA Container Runtime with Docker integration and TensorRT support for INT-8 DLA operations.
