### ISSUE TITLE
Would running this docker allow to run DIGITS on TX2?

### ISSUE THREAD

**Issue by Lonai3190** [Technica-Corporation/Tegra-Docker#4]

**Comment by kgdad** [comment]
According to [this post ](https://devtalk.nvidia.com/default/topic/1007431/jetson-tx2/issues-installing-digits-on-tx2/post/5142204/#5142204) DIGITS isn't officially supported on ARM and thus the TX2 or any other Jetson platform.  Looks like the standard workflow would be to deploy DIGITS on a workstation, build your model, then deploy that model on the TX2 for inference.

You can give it a shot though and see if you can get it working.  Here is  a [DIGITS Dockerfile](https://gitlab.com/nvidia/digits/blob/master/6.0/Dockerfile) that you can use as a template to try it out.  Will need to change somethings but it's a great start.
