### ISSUE TITLE
Tegra TX2 does not reboot

### ISSUE THREAD

**Issue by bhateharsh** [Technica-Corporation/Tegra-Docker#5]
Hello,

I could successfully compile the custom kernel and copied the said files to the TX-2 according to the instructions. Everything goes without a hitch until point 6 where I am supposed to reboot the TX-2 for the new kernel to take effect. 

Once I reboot, the device refuses to reboot and requires a fresh new flash of the OS. 

I'm using JetPack 3.2 for Tegra TX2 and compiling on an Ubuntu 16.04 x86 based system. 

Thanks!

**Comment by kgdad** [comment]
- Are there any boot errors that you can see? 
- Ensure that the Image and zImage files are written correctly to the /boot directory and they have the correct permissions

**Comment by bhateharsh** [comment]
Thank you for your response. The issue was solved.

Thanks again!
