### ISSUE TITLE
Performance drop using docker on TX-2

### ISSUE THREAD

**Issue by ofirule** [Technica-Corporation/Tegra-Docker#6]
We are trying to move our code to run on Docker with the GPU on the Jetson TX2, we managed to run it but the GPU performance is 50% of what we had before in terms of detection FPS (from 23FPS to 11FPS).
We are using JetPack ver 3.2. 
Any help would be appriciated

**Comment by kgdad** [comment]
I haven't done any performance tests using docker on the TX2 and the GPU.  Can you try running the particles demo from the CUDA samples in both directly on the host and in a container?  The instructions for running in a container are at the bottom of this repository.

I was able to get similar performance in the container as I did out of the container.

**Comment by ofirule** [comment]
After further investigation we found out that the performance loss caused by some other issues, not related to docker, and after we fixed those we had similar performance using docker.

Sorry for the false alarm,
thank you for your help
