### ISSUE TITLE
bash: tx2-docker: command not found

### ISSUE THREAD

**Issue by yi2ha** [Technica-Corporation/Tegra-Docker#7]
I get this  from  my tx2. Is there anythiny I miss ? Thx.

`nvidia@tegra-ubuntu:~/tx2_docker/particles$ sudo docker run particles/cudaSamples/particles: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
nvidia@tegra-ubuntu:~/tx2_docker/particles$ 
`

`nvidia@tegra-ubuntu:~/tx2_docker/particles$ tx2-docker run particles
bash: tx2-docker: command not found
nvidia@tegra-ubuntu:~/tx2_docker/particles$ 
`
I can  get the same out  put  when runing deviceQuery.
`deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS
nvidia@tegra-ubuntu:~/tx2_docker/deviceQuery$ `

**Comment by yi2ha** [comment]
Get some tips from this URL, and I get the tx2-docker work .
https://stackoverflow.com/questions/19538669/run-bash-script-with-sh


nvidia@tegra-ubuntu:~/tx2_docker/particles$ sudo chmod +x tx2-docker
[sudo] password for nvidia: 
nvidia@tegra-ubuntu:~/tx2_docker/particles$ ls
data  Dockerfile  particles  tx2-docker
nvidia@tegra-ubuntu:~/tx2_docker/particles$ ./tx2-docker run particles
Running an nvidia docker image
docker run -e LD_LIBRARY_PATH=:/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/tegra:/usr/local/cuda/lib64 --net=host  -v /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu -v /usr/local/cuda/lib64:/usr/local/cuda/lib64  --device=/dev/nvhost-ctrl --device=/dev/nvhost-ctrl-gpu --device=/dev/nvhost-prof-gpu --device=/dev/nvmap --device=/dev/nvhost-gpu --device=/dev/nvhost-as-gpu particles
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
nvidia@tegra-ubuntu:~/tx2_docker/particles$ sudo ./tx2-docker run particles
Running an nvidia docker image
docker run -e LD_LIBRARY_PATH=:/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/tegra:/usr/local/cuda/lib64 --net=host  -v /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu -v /usr/local/cuda/lib64:/usr/local/cuda/lib64  --device=/dev/nvhost-ctrl --device=/dev/nvhost-ctrl-gpu --device=/dev/nvhost-prof-gpu --device=/dev/nvmap --device=/dev/nvhost-gpu --device=/dev/nvhost-as-gpu particles

**Comment by Sjoerdtvanvliet** [comment]
How did you fix the libGL.so.1: cannot open shared object file: No such file or directory error?
